#!/bin/bash

IMAGENAME="kwkoo/solver"
VERSION="0.1"

cd `dirname $0`
BASE=`pwd`

docker build \
	--rm \
	-t ${IMAGENAME}:${VERSION} \
	.

echo "Done building image, sleeping..."
sleep 2
echo "Removing intermediate build container"
docker images -f label=builder=true | xargs docker rmi
